import { StepInstruction, NormalInstruction } from "../Instructions";

// Secrets manager secrets should at least be encrypted with KMS customer managed keys.	
export const SecretEncryptionCustomerKms = () => {
   
    return (
        <>
            <NormalInstruction instruction="Perform the following via AWS 
            Management Console to encrypt a Secrets Manager secret 
            using a KMS Customer Managed Key:"/>

            <StepInstruction stepNumber={"1."} instruction="Sign in to the 
            AWS Management Console."/>
            <StepInstruction stepNumber={"2."} instruction="Navigate to IAM dashboard
             at https://console.aws.amazon.com/iam/."/>
            <StepInstruction stepNumber={"3."} instruction="In the left navigation panel 
            click **Encryption Keys**."/>
            <StepInstruction stepNumber={"4."} instruction="Select the appropriate AWS region
             from the **Filter** menu (must match the region where the secret that you want to 
            encrypt with the new key was created)."/>
            <StepInstruction stepNumber={"5."} instruction="Click **Create Key** button from the 
            dashboard top menu."/>
            <StepInstruction stepNumber={"6."} instruction="In the **Alias (required)** and 
            **Description** fields, enter a unique name (alias) and a description for the new CMK, 
            then click the Next Step button."/>
            <StepInstruction stepNumber={"7."} instruction="Under **Key Administrators** section, 
            select which IAM users and/or roles can administer the new CMK, 
            then click **Next Step**."/>
            <StepInstruction stepNumber={"8."} instruction="Under **This Account** section, 
            select which IAM users and/or roles can use the new CMK to encrypt/decrypt 
            the secret data with the AWS KMS API."/>
            <StepInstruction stepNumber={"9."} instruction="(Optional) Under **External Accounts**
            section, click **Add an External Account** and enter an external account ID in order
            to add another AWS account that can use this CMK to encrypt/decrypt the Secrets Manager 
            secret information. The owners of the external AWS accounts must also provide access
            to this CMK by creating appropriate policies for their IAM users."/>
            <StepInstruction stepNumber={"10."} instruction="Click **Next Step** to continue 
            the process."/>
            <StepInstruction stepNumber={"11."} instruction="Under **Preview Key Policy** section, 
            review the key policy generated by AWS then click **Finish** to create your new CMK. 
            Once the key is created, the KMS dashboard will display a confirmation message: 
            **Your master key was created successfully. Alias: <cmk-alias>**."/>
            <StepInstruction stepNumber={"12."} instruction="Once the customer-managed CMK has 
            been created, navigate to AWS Secrets Manager service dashboard at 
            https://console.aws.amazon.com/secretsmanager/."/>
            <StepInstruction stepNumber={"13."} instruction="In the navigation panel, 
            select **Secrets**."/>
            <StepInstruction stepNumber={"14."} instruction="Choose the Secrets Manager secret
            that you want to reconfigure, then click on its name (link) to access its 
            configuration details."/>
            <StepInstruction stepNumber={"15."} instruction="On the selected secret configuration 
            page, click the **Actions** dropdown menu from the dashboard top menu and select 
            **Edit encryption key** option."/>
            <StepInstruction stepNumber={"16."} instruction="In the **Edit encryption key** dialog box,
             choose the name (alias) of the customer-managed KMS Customer Master Key created 
             earlier from the **Select the encryption key** dropdown list,
              then click **Save** to apply the changes."/>
            <StepInstruction stepNumber={"17."} instruction="Repeat steps no. 14 – 16 for each Secrets Manager secret 
            that you want to encrypt using your new KMS CMK, available in the current AWS region."/>
            <StepInstruction stepNumber={"18."} instruction="Change the AWS region from the navigation bar 
            and repeat the process for other regions."/>  
        </>  
    )

}