FROM node:18.18.1-alpine

WORKDIR /usr/src/app

# Unfortunately the outputs of yarn install get overriden by the mount,
# so you have to run yarn install from outside of Docker anyways...
COPY package.json .
RUN yarn install

EXPOSE 3000
# This currently relies on volume mount of frontend directory
ENTRYPOINT ["yarn", "run", "start"]


